apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argus
labels:
  - pairs:
      app.kubernetes.io/name: argus
      app.kubernetes.io/part-of: argus
    includeSelectors: false
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - api.yaml
  - worker.yaml
  - scheduler.yaml
  - operator-jobs.yaml
  - scaling.yaml
  - network-policies.yaml
