"""Migrations are reversible and the ORM models match the migrated schema (no drift)."""

from __future__ import annotations

import asyncio
import secrets
from collections.abc import AsyncIterator

import asyncpg
import pytest
from alembic import command
from sqlalchemy.engine import make_url

from argus.core.config import Settings
from argus.infrastructure.db.migrations import alembic_config
from tests.support import (
    TEST_APP_ROLE,
    TEST_OWNER_ROLE,
    TEST_ROLE_PASSWORD,
    DatabaseURLs,
    make_settings,
    with_credentials,
)

pytestmark = pytest.mark.integration


@pytest.fixture
async def scratch_settings(database_urls: DatabaseURLs) -> AsyncIterator[Settings]:
    admin = make_url(database_urls.admin)
    server_admin = admin.set(database="postgres").render_as_string(hide_password=False)
    name = f"argus_mig_{secrets.token_hex(4)}"
    conn = await asyncpg.connect(server_admin)
    try:
        await conn.execute(f"CREATE DATABASE {name} OWNER {TEST_OWNER_ROLE}")
    finally:
        await conn.close()
    db_admin = admin.set(database=name).render_as_string(hide_password=False)
    conn = await asyncpg.connect(db_admin)
    try:
        await conn.execute("CREATE EXTENSION IF NOT EXISTS vector")
    finally:
        await conn.close()
    base = database_urls.admin
    yield make_settings(
        database={
            "url": with_credentials(
                base,
                user=TEST_APP_ROLE,
                password=TEST_ROLE_PASSWORD,
                database=name,
                driver="postgresql+asyncpg",
            ),
            "migration_url": with_credentials(
                base,
                user=TEST_OWNER_ROLE,
                password=TEST_ROLE_PASSWORD,
                database=name,
                driver="postgresql+asyncpg",
            ),
            "app_role": TEST_APP_ROLE,
        }
    )
    conn = await asyncpg.connect(server_admin)
    try:
        await conn.execute(
            "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1", name
        )
        await conn.execute(f"DROP DATABASE IF EXISTS {name}")
    finally:
        await conn.close()


async def test_upgrade_downgrade_upgrade_cycle(scratch_settings: Settings) -> None:
    config = alembic_config(scratch_settings)
    await asyncio.to_thread(command.upgrade, config, "head")
    await asyncio.to_thread(command.downgrade, config, "base")
    await asyncio.to_thread(command.upgrade, config, "head")


async def test_models_match_migrations(scratch_settings: Settings) -> None:
    config = alembic_config(scratch_settings)
    await asyncio.to_thread(command.upgrade, config, "head")
    # raises AutogenerateDiffsDetected when a model changed without a migration
    await asyncio.to_thread(command.check, config)
