"""Object store protocol, the local-filesystem backend and the backend factory.

Object keys are generated by the server (``org/<uuid>/project/<uuid>/documents/<uuid>``) and are
validated again here, so a bug elsewhere can never turn a key into a path outside the storage
root: only lower-case ASCII segments are accepted, ``..`` is impossible, and the resolved path
must stay inside the root.
"""

from __future__ import annotations

import asyncio
import os
import re
import tempfile
from pathlib import Path
from typing import Final, Protocol

from argus.core.config import StorageSettings

_KEY: Final = re.compile(r"[a-z0-9][a-z0-9_-]{0,127}(?:/[a-z0-9][a-z0-9_-]{0,127}){0,15}")


class StorageError(Exception):
    """The backend failed (retryable)."""


class ObjectNotFound(StorageError):
    pass


def validate_key(key: str) -> str:
    if not _KEY.fullmatch(key):
        msg = "invalid object key"
        raise ValueError(msg)
    return key


class ObjectStore(Protocol):
    name: str

    async def put(self, key: str, data: bytes) -> None: ...

    async def get(self, key: str) -> bytes: ...

    async def delete(self, key: str) -> None:
        """Idempotent: deleting a missing object succeeds."""
        ...

    async def exists(self, key: str) -> bool: ...

    async def aclose(self) -> None: ...


class LocalObjectStore:
    """Files under one root directory, written atomically (temp file + rename), mode 0600."""

    name = "local"

    def __init__(self, root: Path) -> None:
        self._root = root.resolve()

    def _path(self, key: str) -> Path:
        path = (self._root / validate_key(key)).resolve()
        if not path.is_relative_to(self._root):  # defence in depth; the pattern already forbids it
            msg = "object key escapes the storage root"
            raise ValueError(msg)
        return path

    @staticmethod
    def _write(path: Path, data: bytes) -> None:
        path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        fd, name = tempfile.mkstemp(dir=path.parent, prefix=".upload-")  # created 0600
        temporary = Path(name)
        try:
            with os.fdopen(fd, "wb") as handle:
                handle.write(data)
                handle.flush()
                os.fsync(handle.fileno())
            temporary.replace(path)
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise

    async def put(self, key: str, data: bytes) -> None:
        path = self._path(key)
        try:
            await asyncio.to_thread(self._write, path, data)
        except OSError as exc:
            raise StorageError(f"write failed: {type(exc).__name__}") from exc

    async def get(self, key: str) -> bytes:
        path = self._path(key)
        try:
            return await asyncio.to_thread(path.read_bytes)
        except FileNotFoundError:
            raise ObjectNotFound(key) from None
        except OSError as exc:
            raise StorageError(f"read failed: {type(exc).__name__}") from exc

    async def delete(self, key: str) -> None:
        path = self._path(key)
        try:
            await asyncio.to_thread(path.unlink, True)
        except OSError as exc:
            raise StorageError(f"delete failed: {type(exc).__name__}") from exc

    async def exists(self, key: str) -> bool:
        return await asyncio.to_thread(self._path(key).is_file)

    async def aclose(self) -> None:
        return None


def create_object_store(settings: StorageSettings) -> ObjectStore:
    if settings.backend == "s3":
        # Imported lazily: boto3 is an optional dependency (``pip install argus[s3]``).
        from argus.infrastructure.storage.s3 import S3ObjectStore

        return S3ObjectStore.from_settings(settings)
    return LocalObjectStore(settings.local_root)
