"""Tenancy: organisations, members, invitations, projects, service accounts, API keys.

Security in this revision:
* RLS on every tenant table (fail closed without `argus.org_id`);
* organisations and memberships are additionally readable by their own members, so "list my
  organisations" works before an organisation is selected;
* composite same-tenant foreign keys (project members, API keys of service accounts);
* two narrow SECURITY DEFINER functions for the only cross-tenant lookups the platform needs,
  each returning a single row selected by a high-entropy secret digest.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-04
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from argus.infrastructure.db import migration_support as ms

_TENANT_TABLES = ("invitations", "projects", "project_members", "service_accounts", "api_keys")

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="active", nullable=False),
        sa.Column("plan", sa.String(length=24), server_default="free", nullable=False),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("deletion_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9-]{1,46}[a-z0-9]$'", name=op.f("ck_organizations_slug_format")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'pending_deletion')",
            name=op.f("ck_organizations_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "invitations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'analyst', 'viewer')", name=op.f("ck_invitations_role")
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_invitations_email_lowercase")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_invitations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitations_token_hash")),
    )
    op.create_index(
        "uq_invitations_pending",
        "invitations",
        ["organization_id", "email"],
        unique=True,
        postgresql_where=sa.text("accepted_at IS NULL AND revoked_at IS NULL"),
    )
    op.create_table(
        "organization_members",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'analyst', 'viewer')",
            name=op.f("ck_organization_members_role"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_members_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_organization_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("organization_id", "user_id", name=op.f("pk_organization_members")),
    )
    op.create_index(
        op.f("ix_organization_members_user_id"), "organization_members", ["user_id"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "visibility", sa.String(length=16), server_default="organization", nullable=False
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "visibility IN ('organization', 'restricted')", name=op.f("ck_projects_visibility")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_projects_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_projects_organization_id_id")),
        sa.UniqueConstraint(
            "organization_id", "name", name=op.f("uq_projects_organization_id_name")
        ),
    )
    op.create_index(
        "ix_projects_org_created", "projects", ["organization_id", "created_at"], unique=False
    )
    op.create_table(
        "service_accounts",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role <> 'owner'", name=op.f("ck_service_accounts_not_owner")),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'analyst', 'viewer')", name=op.f("ck_service_accounts_role")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_service_accounts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_accounts")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_service_accounts_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id", "name", name=op.f("uq_service_accounts_organization_id_name")
        ),
    )
    op.create_table(
        "api_keys",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("key_id", sa.String(length=16), nullable=False),
        sa.Column("secret_hash", sa.LargeBinary(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("service_account_id", sa.Uuid(), nullable=True),
        sa.Column("scopes", sa.ARRAY(sa.String(length=48)), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "num_nonnulls(owner_user_id, service_account_id) = 1",
            name=op.f("ck_api_keys_exactly_one_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "service_account_id"],
            ["service_accounts.organization_id", "service_accounts.id"],
            name=op.f("fk_api_keys_organization_id_service_account_id_service_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_api_keys_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_api_keys_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_id", name=op.f("uq_api_keys_key_id")),
    )
    op.create_index(
        "ix_api_keys_org_created", "api_keys", ["organization_id", "created_at"], unique=False
    )
    op.create_table(
        "project_members",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("added_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('editor', 'viewer')", name=op.f("ck_project_members_role")),
        sa.ForeignKeyConstraint(
            ["organization_id", "project_id"],
            ["projects.organization_id", "projects.id"],
            name=op.f("fk_project_members_organization_id_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "user_id"],
            ["organization_members.organization_id", "organization_members.user_id"],
            name=op.f("fk_project_members_organization_id_user_id_organization_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "user_id", name=op.f("pk_project_members")),
    )
    op.create_index(
        "ix_project_members_org_user",
        "project_members",
        ["organization_id", "user_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    role = ms.app_role()
    for table in ("organizations", "organization_members", *_TENANT_TABLES):
        op.execute(ms.grant_dml(table))

    # organisations: the row's own id is the tenant id
    op.execute("ALTER TABLE organizations ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON organizations "
        "USING (id = argus_current_org()) WITH CHECK (id = argus_current_org())"
    )
    op.execute(
        "CREATE POLICY member_read ON organizations FOR SELECT USING (EXISTS ("
        "SELECT 1 FROM organization_members m "
        "WHERE m.organization_id = organizations.id AND m.user_id = argus_current_user()))"
    )
    for statement in ms.tenant_rls("organization_members", also_visible_to_user_column="user_id"):
        op.execute(statement)
    for table in _TENANT_TABLES:
        for statement in ms.tenant_rls(table):
            op.execute(statement)

    # API-key verification before the tenant is known. The caller supplies the key id and the
    # HMAC of the secret; the stored hash is compared here and never returned.
    op.execute(
        """
        CREATE FUNCTION argus_authenticate_api_key(p_key_id text, p_secret_hash bytea)
        RETURNS TABLE (
            id uuid, organization_id uuid, owner_user_id uuid, service_account_id uuid,
            scopes text[], expires_at timestamptz, revoked_at timestamptz,
            last_used_at timestamptz, org_status text, sa_disabled_at timestamptz
        )
        LANGUAGE sql STABLE SECURITY DEFINER
        SET search_path = pg_catalog, public
        AS $$
            SELECT k.id, k.organization_id, k.owner_user_id, k.service_account_id,
                   k.scopes::text[], k.expires_at, k.revoked_at, k.last_used_at,
                   o.status::text, s.disabled_at
            FROM public.api_keys k
            JOIN public.organizations o ON o.id = k.organization_id
            LEFT JOIN public.service_accounts s
                   ON s.organization_id = k.organization_id AND s.id = k.service_account_id
            WHERE k.key_id = p_key_id AND k.secret_hash = p_secret_hash
        $$
        """
    )
    # Invitation acceptance: the invitee is not yet a member of the organisation.
    op.execute(
        """
        CREATE FUNCTION argus_find_invitation(p_token_hash bytea)
        RETURNS TABLE (
            id uuid, organization_id uuid, email text, role text, expires_at timestamptz,
            accepted_at timestamptz, revoked_at timestamptz
        )
        LANGUAGE sql STABLE SECURITY DEFINER
        SET search_path = pg_catalog, public
        AS $$
            SELECT i.id, i.organization_id, i.email::text, i.role::text, i.expires_at,
                   i.accepted_at, i.revoked_at
            FROM public.invitations i
            WHERE i.token_hash = p_token_hash
        $$
        """
    )
    for function in ("argus_authenticate_api_key(text, bytea)", "argus_find_invitation(bytea)"):
        op.execute(f"REVOKE ALL ON FUNCTION {function} FROM PUBLIC")
        op.execute(f"GRANT EXECUTE ON FUNCTION {function} TO {role}")


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS argus_find_invitation(bytea)")
    op.execute("DROP FUNCTION IF EXISTS argus_authenticate_api_key(text, bytea)")
    # this policy on organizations reads organization_members: drop it before that table
    op.execute("DROP POLICY IF EXISTS member_read ON organizations")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_project_members_org_user", table_name="project_members")
    op.drop_table("project_members")
    op.drop_index("ix_api_keys_org_created", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("service_accounts")
    op.drop_index("ix_projects_org_created", table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_organization_members_user_id"), table_name="organization_members")
    op.drop_table("organization_members")
    op.drop_index(
        "uq_invitations_pending",
        table_name="invitations",
        postgresql_where=sa.text("accepted_at IS NULL AND revoked_at IS NULL"),
    )
    op.drop_table("invitations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
