"""Job queue, idempotency keys, research jobs, plans, steps and approvals.

`jobs` and `idempotency_keys` are infrastructure tables (identifiers only, no RLS); the research
tables are tenant tables with RLS and composite same-tenant foreign keys.

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from argus.infrastructure.db import migration_support as ms

_TENANT_TABLES = ("research_jobs", "research_plans", "research_steps", "approval_requests")

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("principal_key", sa.String(length=80), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.LargeBinary(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("principal_key", "key", name=op.f("pk_idempotency_keys")),
    )
    op.create_index("ix_idempotency_keys_expires", "idempotency_keys", ["expires_at"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("queue", sa.String(length=32), nullable=False),
        sa.Column("task", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="queued", nullable=False),
        sa.Column("priority", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("timeout_s", sa.Integer(), nullable=False),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("dedup_key", sa.String(length=200), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'dead', 'cancelled')",
            name=op.f("ck_jobs_status"),
        ),
        sa.CheckConstraint("max_attempts BETWEEN 1 AND 50", name=op.f("ck_jobs_max_attempts")),
        sa.CheckConstraint("timeout_s BETWEEN 1 AND 86400", name=op.f("ck_jobs_timeout")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_jobs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(
        "ix_jobs_claim",
        "jobs",
        ["queue", sa.literal_column("priority DESC"), "run_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        "ix_jobs_leases",
        "jobs",
        ["locked_until"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index("ix_jobs_organization", "jobs", ["organization_id"], unique=False)
    op.create_index(
        "uq_jobs_active_dedup",
        "jobs",
        ["dedup_key"],
        unique=True,
        postgresql_where=sa.text("dedup_key IS NOT NULL AND status IN ('queued', 'running')"),
    )
    op.create_table(
        "research_jobs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_api_key_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="queued", nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column("progress", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("budget_usd", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "spent_usd", sa.Numeric(precision=14, scale=6), server_default="0", nullable=False
        ),
        sa.Column("input_tokens", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("max_sources", sa.Integer(), nullable=False),
        sa.Column(
            "options", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("queue_job_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=48), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('web', 'documents', 'hybrid')", name=op.f("ck_research_jobs_mode")
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'awaiting_approval', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_research_jobs_status"),
        ),
        sa.CheckConstraint("budget_usd > 0", name=op.f("ck_research_jobs_budget_positive")),
        sa.CheckConstraint("progress BETWEEN 0 AND 100", name=op.f("ck_research_jobs_progress")),
        sa.ForeignKeyConstraint(
            ["organization_id", "project_id"],
            ["projects.organization_id", "projects.id"],
            name=op.f("fk_research_jobs_organization_id_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_jobs")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_research_jobs_organization_id_id")
        ),
    )
    op.create_index(
        "ix_research_jobs_active",
        "research_jobs",
        ["organization_id", "status"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued', 'running', 'awaiting_approval')"),
    )
    op.create_index(
        "ix_research_jobs_project_created",
        "research_jobs",
        ["organization_id", "project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "approval_requests",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'expired')",
            name=op.f("ck_approval_requests_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "job_id"],
            ["research_jobs.organization_id", "research_jobs.id"],
            name=op.f("fk_approval_requests_organization_id_job_id_research_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_requests")),
    )
    op.create_index(
        "ix_approval_requests_pending",
        "approval_requests",
        ["organization_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "research_plans",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=True),
        sa.Column("prompt_version", sa.String(length=80), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "job_id"],
            ["research_jobs.organization_id", "research_jobs.id"],
            name=op.f("fk_research_plans_organization_id_job_id_research_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_plans")),
        sa.UniqueConstraint("job_id", "version", name=op.f("uq_research_plans_job_id_version")),
    )
    op.create_table(
        "research_steps",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=48), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "output", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("error_code", sa.String(length=48), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed', 'skipped')",
            name=op.f("ck_research_steps_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "job_id"],
            ["research_jobs.organization_id", "research_jobs.id"],
            name=op.f("fk_research_steps_organization_id_job_id_research_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_steps")),
        sa.UniqueConstraint("job_id", "key", name=op.f("uq_research_steps_job_id_key")),
    )
    # ### end Alembic commands ###

    for table in ("jobs", "idempotency_keys", *_TENANT_TABLES):
        op.execute(ms.grant_dml(table))
    for table in _TENANT_TABLES:
        for statement in ms.tenant_rls(table):
            op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("research_steps")
    op.drop_table("research_plans")
    op.drop_index("ix_approval_requests_pending", table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index("ix_research_jobs_project_created", table_name="research_jobs")
    op.drop_index(
        "ix_research_jobs_active",
        table_name="research_jobs",
        postgresql_where=sa.text("status IN ('queued', 'running', 'awaiting_approval')"),
    )
    op.drop_table("research_jobs")
    op.drop_index(
        "uq_jobs_active_dedup",
        table_name="jobs",
        postgresql_where=sa.text("dedup_key IS NOT NULL AND status IN ('queued', 'running')"),
    )
    op.drop_index("ix_jobs_organization", table_name="jobs")
    op.drop_index(
        "ix_jobs_leases", table_name="jobs", postgresql_where=sa.text("status = 'running'")
    )
    op.drop_index("ix_jobs_claim", table_name="jobs", postgresql_where=sa.text("status = 'queued'"))
    op.drop_table("jobs")
    op.drop_index("ix_idempotency_keys_expires", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
