"""Source registry (provenance), content snapshots and per-organisation domain policies.

All three are tenant tables: RLS on ``organization_id`` plus composite same-tenant foreign keys
(a snapshot can only point at a source of its own organisation; a source only at a project of
its own organisation). ``discovered_by_job_id`` is provenance metadata, deliberately without a
foreign key: deleting a research job must not delete the evidence it collected.

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-04
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from argus.infrastructure.db import migration_support as ms

_TENANT_TABLES = ("domain_policies", "sources", "source_snapshots")

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_policies",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("policy", sa.String(length=24), nullable=False),
        sa.Column("reputation_override", sa.Float(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "policy IN ('allow', 'block', 'require_approval')",
            name=op.f("ck_domain_policies_policy"),
        ),
        sa.CheckConstraint(
            "reputation_override IS NULL OR reputation_override BETWEEN 0 AND 1",
            name=op.f("ck_domain_policies_reputation"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_domain_policies_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain_policies")),
        sa.UniqueConstraint(
            "organization_id", "domain", name=op.f("uq_domain_policies_organization_id_domain")
        ),
    )
    op.create_table(
        "sources",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.LargeBinary(), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("last_error_code", sa.String(length=48), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("publisher", sa.String(length=200), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("reputation", sa.Float(), server_default="0.5", nullable=False),
        sa.Column("trust_tier", sa.String(length=16), server_default="unknown", nullable=False),
        sa.Column("injection_level", sa.String(length=8), server_default="none", nullable=False),
        sa.Column("injection_score", sa.Float(), server_default="0", nullable=False),
        sa.Column("discovered_via", sa.String(length=16), server_default="manual", nullable=False),
        sa.Column("discovered_by_job_id", sa.Uuid(), nullable=True),
        sa.Column("search_query", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetch_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discovered_via IN ('manual', 'search', 'link', 'monitor')",
            name=op.f("ck_sources_discovered_via"),
        ),
        sa.CheckConstraint(
            "injection_level IN ('none', 'low', 'medium', 'high')",
            name=op.f("ck_sources_injection_level"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'fetched', 'failed', 'blocked')", name=op.f("ck_sources_status")
        ),
        sa.CheckConstraint(
            "trust_tier IN ('high', 'medium', 'low', 'unknown')", name=op.f("ck_sources_trust_tier")
        ),
        sa.CheckConstraint("reputation BETWEEN 0 AND 1", name=op.f("ck_sources_reputation")),
        sa.ForeignKeyConstraint(
            ["organization_id", "project_id"],
            ["projects.organization_id", "projects.id"],
            name=op.f("fk_sources_organization_id_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_sources_organization_id_id")),
        sa.UniqueConstraint(
            "organization_id",
            "project_id",
            "url_hash",
            name=op.f("uq_sources_organization_id_project_id_url_hash"),
        ),
    )
    op.create_index("ix_sources_domain", "sources", ["organization_id", "domain"], unique=False)
    op.create_index(
        "ix_sources_project_created",
        "sources",
        ["organization_id", "project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "source_snapshots",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("content_hash", sa.LargeBinary(), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("server_ip", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("injection_score", sa.Float(), server_default="0", nullable=False),
        sa.Column("injection_level", sa.String(length=8), server_default="none", nullable=False),
        sa.Column(
            "injection_signals",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "injection_level IN ('none', 'low', 'medium', 'high')",
            name=op.f("ck_source_snapshots_injection_level"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "source_id"],
            ["sources.organization_id", "sources.id"],
            name=op.f("fk_source_snapshots_organization_id_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_snapshots")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_source_snapshots_organization_id_id")
        ),
        sa.UniqueConstraint(
            "source_id", "content_hash", name=op.f("uq_source_snapshots_source_id_content_hash")
        ),
    )
    op.create_index(
        "ix_source_snapshots_source_time",
        "source_snapshots",
        ["organization_id", "source_id", "fetched_at"],
        unique=False,
    )
    # ### end Alembic commands ###
    for table in _TENANT_TABLES:
        op.execute(ms.grant_dml(table))
        for statement in ms.tenant_rls(table):
            op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_source_snapshots_source_time", table_name="source_snapshots")
    op.drop_table("source_snapshots")
    op.drop_index("ix_sources_project_created", table_name="sources")
    op.drop_index("ix_sources_domain", table_name="sources")
    op.drop_table("sources")
    op.drop_table("domain_policies")
    # ### end Alembic commands ###
