"""Uploaded documents: lifecycle, scan result, extracted text and injection assessment.

A tenant table with RLS and a composite same-tenant foreign key to its project. The blob itself
lives in object storage under a server-generated key, encrypted by the application (ADR 0009);
``storage_key`` is unique across the whole table so two rows can never share one object.

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-04
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from argus.infrastructure.db import migration_support as ms

_TENANT_TABLES = ("documents",)

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.LargeBinary(), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("classification", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending_scan", nullable=False),
        sa.Column("error_code", sa.String(length=48), nullable=True),
        sa.Column("scan_engine", sa.String(length=32), nullable=True),
        sa.Column("scan_signature", sa.String(length=200), nullable=True),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("language", sa.String(length=35), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("text_chars", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("injection_score", sa.Float(), server_default="0", nullable=False),
        sa.Column("injection_level", sa.String(length=8), server_default="none", nullable=False),
        sa.Column(
            "injection_signals",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "injection_level IN ('none', 'low', 'medium', 'high')",
            name=op.f("ck_documents_injection_level"),
        ),
        sa.CheckConstraint(
            "kind IN ('pdf', 'docx', 'text', 'markdown', 'csv', 'json', 'html')",
            name=op.f("ck_documents_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('pending_scan', 'processing', 'ready', 'failed', 'quarantined')",
            name=op.f("ck_documents_status"),
        ),
        sa.CheckConstraint("byte_size > 0", name=op.f("ck_documents_byte_size")),
        sa.CheckConstraint(
            "classification BETWEEN 0 AND 3", name=op.f("ck_documents_classification")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "project_id"],
            ["projects.organization_id", "projects.id"],
            name=op.f("fk_documents_organization_id_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_documents_organization_id_id")),
        sa.UniqueConstraint(
            "organization_id",
            "project_id",
            "sha256",
            name=op.f("uq_documents_organization_id_project_id_sha256"),
        ),
        sa.UniqueConstraint("storage_key", name=op.f("uq_documents_storage_key")),
    )
    op.create_index(
        "ix_documents_project_created",
        "documents",
        ["organization_id", "project_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
    for table in _TENANT_TABLES:
        op.execute(ms.grant_dml(table))
        for statement in ms.tenant_rls(table):
            op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_documents_project_created", table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
