"""Knowledge chunks: text, generated full-text vector, embedding and filter attributes.

``document_chunks`` is a tenant table (RLS) whose parents - project, document, source, snapshot -
are composite same-tenant foreign keys with ``ON DELETE CASCADE``, so deleting a document removes
its searchable representation in the same transaction. The HNSW index serves cosine-distance
vector search; the GIN index serves full-text search over a ``tsvector`` that PostgreSQL computes
itself. ``projects.corpus_version`` versions retrieval caches.

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-04
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from argus.infrastructure.db import migration_support as ms

_TENANT_TABLES = ("document_chunks",)

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_chunks",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.LargeBinary(), nullable=False),
        sa.Column("token_estimate", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("classification", sa.SmallInteger(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("injection_level", sa.String(length=8), nullable=False),
        sa.Column("fts_config", sa.String(length=16), nullable=False),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "CASE WHEN fts_config = 'english' THEN to_tsvector('english'::regconfig, text) ELSE to_tsvector('simple'::regconfig, text) END",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("embedding", Vector(1024), nullable=True),
        sa.Column("embedding_model", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(origin = 'document' AND document_id IS NOT NULL AND snapshot_id IS NULL AND source_id IS NULL) OR (origin = 'web' AND document_id IS NULL AND snapshot_id IS NOT NULL AND source_id IS NOT NULL)",
            name=op.f("ck_document_chunks_parent"),
        ),
        sa.CheckConstraint(
            "fts_config IN ('english', 'simple')", name=op.f("ck_document_chunks_fts_config")
        ),
        sa.CheckConstraint(
            "injection_level IN ('none', 'low', 'medium', 'high')",
            name=op.f("ck_document_chunks_injection_level"),
        ),
        sa.CheckConstraint("origin IN ('document', 'web')", name=op.f("ck_document_chunks_origin")),
        sa.CheckConstraint(
            "(embedding IS NULL) = (embedding_model IS NULL)",
            name=op.f("ck_document_chunks_embedding_model"),
        ),
        sa.CheckConstraint("char_end > char_start", name=op.f("ck_document_chunks_offsets")),
        sa.CheckConstraint(
            "classification BETWEEN 0 AND 3", name=op.f("ck_document_chunks_classification")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "document_id"],
            ["documents.organization_id", "documents.id"],
            name=op.f("fk_document_chunks_organization_id_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "project_id"],
            ["projects.organization_id", "projects.id"],
            name=op.f("fk_document_chunks_organization_id_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "snapshot_id"],
            ["source_snapshots.organization_id", "source_snapshots.id"],
            name=op.f("fk_document_chunks_organization_id_snapshot_id_source_snapshots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "source_id"],
            ["sources.organization_id", "sources.id"],
            name=op.f("fk_document_chunks_organization_id_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint(
            "document_id", "ordinal", name=op.f("uq_document_chunks_document_id_ordinal")
        ),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_document_chunks_organization_id_id")
        ),
        sa.UniqueConstraint(
            "snapshot_id", "ordinal", name=op.f("uq_document_chunks_snapshot_id_ordinal")
        ),
    )
    op.create_index("ix_document_chunks_document", "document_chunks", ["document_id"], unique=False)
    op.create_index(
        "ix_document_chunks_embedding",
        "document_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_document_chunks_scope",
        "document_chunks",
        ["organization_id", "project_id", "classification"],
        unique=False,
    )
    op.create_index("ix_document_chunks_snapshot", "document_chunks", ["snapshot_id"], unique=False)
    op.create_index("ix_document_chunks_source", "document_chunks", ["source_id"], unique=False)
    op.create_index(
        "ix_document_chunks_tsv", "document_chunks", ["tsv"], unique=False, postgresql_using="gin"
    )
    op.add_column(
        "projects", sa.Column("corpus_version", sa.BigInteger(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###
    for table in _TENANT_TABLES:
        op.execute(ms.grant_dml(table))
        for statement in ms.tenant_rls(table):
            op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "corpus_version")
    op.drop_index("ix_document_chunks_tsv", table_name="document_chunks", postgresql_using="gin")
    op.drop_index("ix_document_chunks_source", table_name="document_chunks")
    op.drop_index("ix_document_chunks_snapshot", table_name="document_chunks")
    op.drop_index("ix_document_chunks_scope", table_name="document_chunks")
    op.drop_index(
        "ix_document_chunks_embedding",
        table_name="document_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("ix_document_chunks_document", table_name="document_chunks")
    op.drop_table("document_chunks")
    # ### end Alembic commands ###
