"""LLM accounting (per-attempt requests, daily usage) and prompt deployments.

``llm_requests`` and ``llm_usage_daily`` are tenant tables (RLS): an organisation can see what its
research cost, never another's. ``prompt_deployments`` is platform configuration - which prompt
version is active per environment - with no tenant data.

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-04
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from argus.infrastructure.db import migration_support as ms

_TENANT_TABLES = ("llm_requests", "llm_usage_daily")

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_deployments",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deployed_by", sa.String(length=200), nullable=True),
        sa.Column("deployed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version > 0", name=op.f("ck_prompt_deployments_version")),
        sa.PrimaryKeyConstraint("name", "environment", name=op.f("pk_prompt_deployments")),
    )
    op.create_table(
        "llm_requests",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("task", sa.String(length=64), nullable=False),
        sa.Column("prompt_name", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.Integer(), nullable=False),
        sa.Column("prompt_sha256", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("served_model", sa.String(length=64), nullable=True),
        sa.Column("locality", sa.String(length=16), nullable=False),
        sa.Column("classification", sa.SmallInteger(), nullable=False),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("error_code", sa.String(length=48), nullable=True),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "cost_usd", sa.Numeric(precision=14, scale=6), server_default="0", nullable=False
        ),
        sa.Column("latency_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("fallback_used", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('ok', 'refused', 'error', 'retryable_error', 'invalid_output', 'truncated', 'blocked_policy', 'blocked_budget', 'circuit_open')",
            name=op.f("ck_llm_requests_outcome"),
        ),
        sa.CheckConstraint("cost_usd >= 0", name=op.f("ck_llm_requests_cost")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_llm_requests_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_requests")),
    )
    op.create_index("ix_llm_requests_job", "llm_requests", ["job_id"], unique=False)
    op.create_index(
        "ix_llm_requests_org_created",
        "llm_requests",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "llm_usage_daily",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("requests", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("input_tokens", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "cost_usd", sa.Numeric(precision=14, scale=6), server_default="0", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_llm_usage_daily_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "organization_id", "day", "provider", "model", name=op.f("pk_llm_usage_daily")
        ),
    )
    # ### end Alembic commands ###
    for table in _TENANT_TABLES:
        op.execute(ms.grant_dml(table))
        for statement in ms.tenant_rls(table):
            op.execute(statement)
    op.execute(ms.grant_dml("prompt_deployments"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_usage_daily")
    op.drop_index("ix_llm_requests_org_created", table_name="llm_requests")
    op.drop_index("ix_llm_requests_job", table_name="llm_requests")
    op.drop_table("llm_requests")
    op.drop_table("prompt_deployments")
    # ### end Alembic commands ###
