"""Agent execution trail, kill switches, research findings and their citations.

``agent_runs``, ``tool_calls``, ``research_findings`` and ``research_citations`` are tenant tables
(RLS, composite same-tenant foreign keys). Citations cascade from ``document_chunks``: deleting a
document removes every citation that rested on it. ``kill_switches`` holds platform-wide rows
(``organization_id IS NULL``, written by operators with the owner role) and organisation rows:
every organisation can *read* platform switches and its own, but can only *write* its own.

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-05
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from argus.infrastructure.db import migration_support as ms

_TENANT_TABLES = ("agent_runs", "tool_calls", "research_findings", "research_citations")

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("agent", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="running", nullable=False),
        sa.Column("iterations", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tool_calls", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "cost_usd", sa.Numeric(precision=14, scale=6), server_default="0", nullable=False
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'max_iterations', 'max_tool_calls', 'budget', 'timeout', 'killed', 'failed')",
            name=op.f("ck_agent_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_runs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_agent_runs_organization_id_id")),
    )
    op.create_index("ix_agent_runs_job", "agent_runs", ["organization_id", "job_id"], unique=False)
    op.create_table(
        "kill_switches",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("target", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('all', 'agent', 'tool', 'provider', 'model')",
            name=op.f("ck_kill_switches_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_kill_switches_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kill_switches")),
    )
    op.create_index(
        "ix_kill_switches_active",
        "kill_switches",
        ["kind", "target"],
        unique=False,
        postgresql_where="active",
    )
    op.create_table(
        "tool_calls",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("tool", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column(
            "arguments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "result", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("latency_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('ok', 'denied', 'invalid_arguments', 'killed', 'error', 'limit')",
            name=op.f("ck_tool_calls_outcome"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "agent_run_id"],
            ["agent_runs.organization_id", "agent_runs.id"],
            name=op.f("fk_tool_calls_organization_id_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
    )
    op.create_index(
        "ix_tool_calls_run", "tool_calls", ["organization_id", "agent_run_id"], unique=False
    )
    op.create_table(
        "research_findings",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.String(length=8), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_classification", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('fact', 'inference', 'hypothesis', 'opinion')",
            name=op.f("ck_research_findings_kind"),
        ),
        sa.CheckConstraint(
            "evidence_classification BETWEEN 0 AND 3",
            name=op.f("ck_research_findings_evidence_classification"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_research_findings_confidence")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "job_id"],
            ["research_jobs.organization_id", "research_jobs.id"],
            name=op.f("fk_research_findings_organization_id_job_id_research_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_findings")),
        sa.UniqueConstraint(
            "job_id",
            "question_id",
            "ordinal",
            name=op.f("uq_research_findings_job_id_question_id_ordinal"),
        ),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_research_findings_organization_id_id")
        ),
    )
    op.create_index(
        "ix_research_findings_job", "research_findings", ["organization_id", "job_id"], unique=False
    )
    op.create_table(
        "research_citations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("ref", sa.String(length=8), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "chunk_id"],
            ["document_chunks.organization_id", "document_chunks.id"],
            name=op.f("fk_research_citations_organization_id_chunk_id_document_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "finding_id"],
            ["research_findings.organization_id", "research_findings.id"],
            name=op.f("fk_research_citations_organization_id_finding_id_research_findings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_citations")),
    )
    op.create_index("ix_research_citations_chunk", "research_citations", ["chunk_id"], unique=False)
    op.create_index(
        "ix_research_citations_finding",
        "research_citations",
        ["organization_id", "finding_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    for table in _TENANT_TABLES:
        op.execute(ms.grant_dml(table))
        for statement in ms.tenant_rls(table):
            op.execute(statement)
    op.execute(ms.grant_dml("kill_switches"))
    op.execute("ALTER TABLE kill_switches ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY kill_switch_read ON kill_switches FOR SELECT "
        "USING (organization_id IS NULL OR organization_id = argus_current_org())"
    )
    op.execute(
        "CREATE POLICY kill_switch_write ON kill_switches "
        "USING (organization_id = argus_current_org()) "
        "WITH CHECK (organization_id = argus_current_org())"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_research_citations_finding", table_name="research_citations")
    op.drop_index("ix_research_citations_chunk", table_name="research_citations")
    op.drop_table("research_citations")
    op.drop_index("ix_research_findings_job", table_name="research_findings")
    op.drop_table("research_findings")
    op.drop_index("ix_tool_calls_run", table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index("ix_kill_switches_active", table_name="kill_switches", postgresql_where="active")
    op.drop_table("kill_switches")
    op.drop_index("ix_agent_runs_job", table_name="agent_runs")
    op.drop_table("agent_runs")
    # ### end Alembic commands ###
