"""Monitors, monitor targets and changes; in-app notifications.

All four tables are tenant tables (RLS, composite same-tenant foreign keys). Two narrow
SECURITY DEFINER functions cover the only cross-tenant work the scheduler does, returning
identifiers or counts and nothing else:

* ``argus_claim_due_monitors(max_rows)`` - atomically advances due active monitors to their next
  run time (``FOR UPDATE SKIP LOCKED``) and returns ``(organization_id, monitor_id)`` pairs;
* ``argus_purge_read_notifications(cutoff)`` - deletes read notifications older than the cutoff
  and returns how many.

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-05
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from argus.infrastructure.db import migration_support as ms

_TENANT_TABLES = ("monitors", "monitor_targets", "monitor_changes", "notifications")
_FUNCTIONS = ("argus_claim_due_monitors(integer)", "argus_purge_read_notifications(timestamptz)")

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event", sa.String(length=48), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.String(length=2000), nullable=False),
        sa.Column("link", sa.String(length=300), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event IN ('research.job.completed', 'research.job.failed', 'approval.requested', 'monitor.change.detected', 'monitor.paused')",
            name=op.f("ck_notifications_event"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notifications_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_unread",
        "notifications",
        ["organization_id", "user_id"],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.create_index(
        "ix_notifications_user",
        "notifications",
        ["organization_id", "user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "monitors",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("queries", postgresql.ARRAY(sa.String(length=200)), nullable=False),
        sa.Column("topics", postgresql.ARRAY(sa.String(length=16)), nullable=False),
        sa.Column("interval_minutes", sa.Integer(), nullable=False),
        sa.Column("significance_threshold", sa.Float(), nullable=False),
        sa.Column("notify_email", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=48), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_api_key_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('urls', 'search')", name=op.f("ck_monitors_kind")),
        sa.CheckConstraint("status IN ('active', 'paused')", name=op.f("ck_monitors_status")),
        sa.CheckConstraint(
            "interval_minutes BETWEEN 60 AND 10080", name=op.f("ck_monitors_interval")
        ),
        sa.CheckConstraint(
            "significance_threshold BETWEEN 0 AND 1", name=op.f("ck_monitors_threshold")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "project_id"],
            ["projects.organization_id", "projects.id"],
            name=op.f("fk_monitors_organization_id_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monitors")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_monitors_organization_id_id")),
    )
    op.create_index(
        "ix_monitors_due",
        "monitors",
        ["next_run_at"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "ix_monitors_project",
        "monitors",
        ["organization_id", "project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "monitor_targets",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("monitor_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("last_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=16), nullable=True),
        sa.Column("last_error_code", sa.String(length=48), nullable=True),
        sa.Column("discovered", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "monitor_id"],
            ["monitors.organization_id", "monitors.id"],
            name=op.f("fk_monitor_targets_organization_id_monitor_id_monitors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monitor_targets")),
        sa.UniqueConstraint("monitor_id", "url", name=op.f("uq_monitor_targets_monitor_id_url")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_monitor_targets_organization_id_id")
        ),
    )
    op.create_index(
        "ix_monitor_targets_monitor",
        "monitor_targets",
        ["organization_id", "monitor_id"],
        unique=False,
    )
    op.create_table(
        "monitor_changes",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("monitor_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("previous_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("topics", postgresql.ARRAY(sa.String(length=16)), nullable=False),
        sa.Column("significance", sa.Float(), nullable=False),
        sa.Column("summary", sa.String(length=600), nullable=False),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("alerted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="new", nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('new', 'acknowledged', 'dismissed')", name=op.f("ck_monitor_changes_status")
        ),
        sa.CheckConstraint(
            "significance BETWEEN 0 AND 1", name=op.f("ck_monitor_changes_significance")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "monitor_id"],
            ["monitors.organization_id", "monitors.id"],
            name=op.f("fk_monitor_changes_organization_id_monitor_id_monitors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "target_id"],
            ["monitor_targets.organization_id", "monitor_targets.id"],
            name=op.f("fk_monitor_changes_organization_id_target_id_monitor_targets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monitor_changes")),
    )
    op.create_index(
        "ix_monitor_changes_monitor",
        "monitor_changes",
        ["organization_id", "monitor_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
    for table in _TENANT_TABLES:
        op.execute(ms.grant_dml(table))
        for statement in ms.tenant_rls(table):
            op.execute(statement)
    op.execute(
        """
        CREATE FUNCTION argus_claim_due_monitors(max_rows integer)
        RETURNS TABLE (organization_id uuid, monitor_id uuid)
        LANGUAGE sql VOLATILE SECURITY DEFINER
        SET search_path = pg_catalog, public
        AS $$
            UPDATE public.monitors m
               SET next_run_at = now() + make_interval(mins => m.interval_minutes),
                   updated_at = now()
              FROM (SELECT id FROM public.monitors
                     WHERE status = 'active' AND next_run_at <= now()
                     ORDER BY next_run_at
                     LIMIT least(greatest(max_rows, 0), 1000)
                     FOR UPDATE SKIP LOCKED) due
             WHERE m.id = due.id
         RETURNING m.organization_id, m.id
        $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION argus_purge_read_notifications(cutoff timestamptz)
        RETURNS integer
        LANGUAGE sql VOLATILE SECURITY DEFINER
        SET search_path = pg_catalog, public
        AS $$
            WITH deleted AS (
                DELETE FROM public.notifications
                 WHERE read_at IS NOT NULL AND read_at < cutoff
             RETURNING 1
            )
            SELECT count(*)::integer FROM deleted
        $$
        """
    )
    role = ms.app_role()
    for function in _FUNCTIONS:
        op.execute(f"REVOKE ALL ON FUNCTION {function} FROM PUBLIC")
        op.execute(f"GRANT EXECUTE ON FUNCTION {function} TO {role}")


def downgrade() -> None:
    for function in _FUNCTIONS:
        op.execute(f"DROP FUNCTION IF EXISTS {function}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_monitor_changes_monitor", table_name="monitor_changes")
    op.drop_table("monitor_changes")
    op.drop_index("ix_monitor_targets_monitor", table_name="monitor_targets")
    op.drop_table("monitor_targets")
    op.drop_index("ix_monitors_project", table_name="monitors")
    op.drop_index(
        "ix_monitors_due", table_name="monitors", postgresql_where=sa.text("status = 'active'")
    )
    op.drop_table("monitors")
    op.drop_index("ix_notifications_user", table_name="notifications")
    op.drop_index(
        "ix_notifications_unread",
        table_name="notifications",
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.drop_table("notifications")
    # ### end Alembic commands ###
