"""Security centre: audit integrity history, scheduling function, security event types.

* ``audit_verifications`` - one row per verification of an organisation's audit chain (tenant
  table: RLS, cascade with the organisation).
* ``argus_audit_verification_due(max_rows, verified_before)`` - the only cross-tenant read the
  verification job needs: identifiers of organisations (not pending deletion) whose last
  verification is older than ``verified_before``. SECURITY DEFINER, returns ids and nothing else.
* Time indexes on ``agent_runs`` and ``tool_calls`` for the security summary.
* Two notification event types (``security.audit.integrity_failed``,
  ``security.kill_switch.engaged``): CHECK constraints are not autogenerated, so the constraint
  is replaced here.

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-05
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from argus.infrastructure.db import migration_support as ms

_FUNCTION = "argus_audit_verification_due(integer, timestamptz)"
_EVENTS_0011 = (
    "research.job.completed",
    "research.job.failed",
    "approval.requested",
    "monitor.change.detected",
    "monitor.paused",
)
_EVENTS_0012 = (*_EVENTS_0011, "security.audit.integrity_failed", "security.kill_switch.engaged")

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _event_check(events: tuple[str, ...]) -> str:
    return "event IN (" + ", ".join(f"'{event}'" for event in events) + ")"


def upgrade() -> None:
    op.create_table(
        "audit_verifications",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("events", sa.BigInteger(), nullable=False),
        sa.Column("first_broken_seq", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "trigger IN ('scheduled', 'manual')", name=op.f("ck_audit_verifications_trigger")
        ),
        sa.CheckConstraint(
            "(valid AND reason IS NULL AND first_broken_seq IS NULL) OR "
            "(NOT valid AND reason IS NOT NULL)",
            name=op.f("ck_audit_verifications_outcome"),
        ),
        sa.CheckConstraint(
            "events >= 0 AND duration_ms >= 0", name=op.f("ck_audit_verifications_counts")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_verifications_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_verifications")),
    )
    op.create_index(
        "ix_audit_verifications_org_time",
        "audit_verifications",
        ["organization_id", "verified_at"],
        unique=False,
    )
    op.create_index(
        "ix_agent_runs_org_created", "agent_runs", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_tool_calls_org_created", "tool_calls", ["organization_id", "created_at"], unique=False
    )

    op.execute(ms.grant_dml("audit_verifications"))
    for statement in ms.tenant_rls("audit_verifications"):
        op.execute(statement)

    op.drop_constraint(op.f("ck_notifications_event"), "notifications", type_="check")
    op.create_check_constraint(
        op.f("ck_notifications_event"), "notifications", _event_check(_EVENTS_0012)
    )

    op.execute(
        """
        CREATE FUNCTION argus_audit_verification_due(max_rows integer, verified_before timestamptz)
        RETURNS TABLE (organization_id uuid)
        LANGUAGE sql STABLE SECURITY DEFINER
        SET search_path = pg_catalog, public
        AS $$
            SELECT o.id
              FROM public.organizations o
             WHERE o.status <> 'pending_deletion'
               AND NOT EXISTS (
                     SELECT 1 FROM public.audit_verifications v
                      WHERE v.organization_id = o.id AND v.verified_at >= verified_before)
             ORDER BY o.id
             LIMIT least(greatest(max_rows, 0), 1000)
        $$
        """
    )
    role = ms.app_role()
    op.execute(f"REVOKE ALL ON FUNCTION {_FUNCTION} FROM PUBLIC")
    op.execute(f"GRANT EXECUTE ON FUNCTION {_FUNCTION} TO {role}")


def downgrade() -> None:
    op.execute(f"DROP FUNCTION IF EXISTS {_FUNCTION}")
    op.execute(
        "DELETE FROM notifications WHERE event IN "
        "('security.audit.integrity_failed', 'security.kill_switch.engaged')"
    )
    op.drop_constraint(op.f("ck_notifications_event"), "notifications", type_="check")
    op.create_check_constraint(
        op.f("ck_notifications_event"), "notifications", _event_check(_EVENTS_0011)
    )
    op.drop_index("ix_tool_calls_org_created", table_name="tool_calls")
    op.drop_index("ix_agent_runs_org_created", table_name="agent_runs")
    for statement in ms.drop_tenant_rls("audit_verifications"):
        op.execute(statement)
    op.drop_index("ix_audit_verifications_org_time", table_name="audit_verifications")
    op.drop_table("audit_verifications")
