"""Report exports: Markdown, JSON, CSV and PDF, all rendered from the canonical report.

Every text field may carry words chosen by a web page's author, so renderers treat it as data:

* **Markdown** - structural characters are backslash-escaped, so text cannot open links,
  images, HTML or tables; images are never emitted; links appear only in the source appendix,
  only for collected ``http(s)`` URLs (URLs inside text were already defanged at assembly).
* **CSV** - every cell that a spreadsheet would treat as a formula (``= + - @``, tab, carriage
  return) is prefixed with an apostrophe; all cells are quoted.
* **PDF** - generated by fpdf2 (no scripts, no forms); link annotations only for collected source
  URLs. Unicode needs a TrueType font (``ARGUS_REPORTS__PDF_FONT_PATH``; the container ships
  DejaVu Sans); without one, characters outside Latin-1 are replaced.
"""

from __future__ import annotations

import csv
import io
import re
from datetime import datetime
from pathlib import Path
from typing import Final
from urllib.parse import quote, urlsplit

from fpdf import FPDF
from fpdf.enums import WrapMode, XPos, YPos

from argus.modules.research.report_model import ReportDocument, ReportMethodology, ReportSource

_MD_SPECIAL: Final = re.compile(r"([\\`*_{}\[\]()#+\-.!|<>~&:])")
_FORMULA_START: Final = ("=", "+", "-", "@", "\t", "\r")
_EXPLANATIONS: Final = {
    "different_time_periods": "different time periods",
    "different_scope_or_definition": "different scope or definitions",
    "source_reliability": "source reliability",
    "measurement_or_estimate": "measurement or estimate",
    "unresolved": "unresolved",
}


def md(text: str | None) -> str:
    """Escape untrusted text for Markdown (one line, every structural character escaped)."""
    return _MD_SPECIAL.sub(r"\\\1", " ".join((text or "").split()))


def safe_link(url: str | None) -> str | None:
    """A collected source URL usable as a link target, or ``None``."""
    if not url:
        return None
    parts = urlsplit(url)
    if parts.scheme not in {"http", "https"} or not parts.netloc:
        return None
    return quote(url, safe=":/?#@!$&'*+,;=%-._~[]")


def _when(value: datetime | None) -> str:
    return value.date().isoformat() if value is not None else "-"


def _source_title(source: ReportSource) -> str:
    return source.title or source.url or "untitled source"


def _finding_counts(m: ReportMethodology) -> str:
    merged = m.findings_total - m.findings_included - m.findings_rejected
    text = (
        f"{m.findings_total} proposed, {m.findings_included} included, "
        f"{m.findings_rejected} rejected by verification"
    )
    return text + (f", {merged} merged as repeats" if merged > 0 else "")


# ------------------------------------------------------------------------- Markdown
def render_markdown(report: ReportDocument) -> str:
    lines: list[str] = [
        f"# {md(report.title)}",
        "",
        f"**Objective:** {md(report.objective)}",
        "",
        (
            f"Generated {report.generated_at.date().isoformat()} - report version "
            f"{report.version} - overall confidence {report.confidence:.0%} - quality "
            f"{report.quality.overall:.0%}"
        ),
        "",
        "## Executive summary",
        "",
        md(report.executive_summary),
        "",
        "## Findings by question",
    ]
    findings = {finding.ref: finding for finding in report.findings}
    for index, section in enumerate(report.sections, start=1):
        lines += ["", f"### {index}. {md(section.question)}", ""]
        if section.status == "insufficient_evidence":
            lines.append("**Unknown - insufficient evidence.**")
            continue
        lines += [md(section.narrative), ""]
        lines += [
            "| Ref | Kind | Confidence | Support | Statement | Sources |",
            "|---|---|---|---|---|---|",
        ]
        for ref in section.findings:
            finding = findings[ref]
            sources = ", ".join(sorted({c.source for c in finding.citations}))
            contested = " (contested)" if finding.contested else ""
            lines.append(
                f"| {ref} | {finding.kind}{contested} | {finding.confidence:.2f} | "
                f"{finding.support} | {md(finding.statement)} | {sources} |"
            )
    lines += ["", "## Contradictions", ""]
    if not report.contradictions:
        lines.append("No contradictions between sources were found.")
    for conflict in report.contradictions:
        lines.append(
            f"- **{conflict.a} vs {conflict.b}** - {md(conflict.attribute)}: {md(conflict.uncertainty)} "
            f"(explanation: {_EXPLANATIONS.get(conflict.explanation, conflict.explanation)}; "
            f"{md(conflict.rationale)})"
        )
    lines += ["", "## Recommendations", ""]
    if not report.recommendations:
        lines.append("No recommendations.")
    for number, advice in enumerate(report.recommendations, start=1):
        refs = f" ({', '.join(advice.findings)})" if advice.findings else ""
        lines.append(f"{number}. {md(advice.text)}{refs}")
    lines += ["", "## Limitations", ""]
    lines += [f"- {md(limitation)}" for limitation in report.limitations]
    m = report.methodology
    lines += [
        "",
        "## Methodology",
        "",
        f"- Questions: {m.questions} (answered: {m.answered})",
        f"- Findings: {_finding_counts(m)}",
        f"- Sources cited: {m.sources}; contradictions: {m.contradictions}",
        f"- Models: {md(', '.join(m.models)) or '-'}",
        f"- Prompts: {md(', '.join(m.prompts)) or '-'}",
        f"- Human approvals: {md(', '.join(m.approvals)) or 'none'}",
        f"- Model cost: USD {m.cost_usd}",
        "",
        "## Appendix A - Evidence",
        "",
    ]
    for finding in report.findings:
        for citation in finding.citations:
            mark = "verified quote" if citation.verified else "unverified quote"
            lines.append(
                f"- **{finding.ref}** \\[{citation.evidence}\\] {citation.source} ({mark}): "
                f"“{md(citation.quote)}”"
            )
    lines += [
        "",
        "## Appendix B - Sources",
        "",
        "| Key | Source | Type | Published | Retrieved | Reliability | Extraction | Content hash |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for source in report.sources:
        link = safe_link(source.url)
        title = md(_source_title(source))
        cell = f"[{title}]({link})" if link else title
        reliability = (
            f"{source.reliability:.2f} ({source.trust_tier})"
            if source.reliability is not None
            else (source.trust_tier or "-")
        )
        digest = f"sha256:{source.content_hash[:16]}" if source.content_hash else "-"
        lines.append(
            f"| {source.key} | {cell} | {md(source.source_type)} | {_when(source.published_at)} | "
            f"{_when(source.retrieved_at)} | {reliability} | {md(source.extraction_method)} | "
            f"{digest} |"
        )
    return "\n".join(lines) + "\n"


# ----------------------------------------------------------------------------- JSON
def render_json(report: ReportDocument) -> str:
    return report.model_dump_json(indent=2)


# ------------------------------------------------------------------------------ CSV
def csv_cell(value: object) -> str:
    text = "" if value is None else str(value)
    return f"'{text}" if text.startswith(_FORMULA_START) else text


def render_csv(report: ReportDocument) -> str:
    questions = {section.question_id: section.question for section in report.sections}
    urls = {source.key: source.url or "" for source in report.sources}
    buffer = io.StringIO()
    writer = csv.writer(buffer, quoting=csv.QUOTE_ALL, lineterminator="\r\n")
    writer.writerow(
        [
            "ref",
            "question_id",
            "question",
            "kind",
            "confidence",
            "support",
            "contested",
            "statement",
            "sources",
            "source_urls",
            "quote",
        ]
    )
    for finding in report.findings:
        keys = sorted({c.source for c in finding.citations})
        writer.writerow(
            [
                csv_cell(value)
                for value in (
                    finding.ref,
                    finding.question_id,
                    questions.get(finding.question_id, ""),
                    finding.kind,
                    f"{finding.confidence:.2f}",
                    finding.support,
                    "yes" if finding.contested else "no",
                    finding.statement,
                    " ".join(keys),
                    " ".join(urls.get(key, "") for key in keys).strip(),
                    finding.citations[0].quote if finding.citations else "",
                )
            ]
        )
    return buffer.getvalue()


# ------------------------------------------------------------------------------ PDF
class _Pdf:
    def __init__(self, font_path: Path | None) -> None:
        self.doc = FPDF(format="A4")
        self.doc.set_margins(18, 16, 18)
        self.doc.set_auto_page_break(auto=True, margin=16)
        self.unicode = font_path is not None and font_path.is_file()
        if font_path is not None and self.unicode:
            self.doc.add_font("ArgusSans", "", str(font_path))
            self.family = "ArgusSans"
        else:
            self.family = "helvetica"
        self.doc.add_page()

    def text(self, value: str) -> str:
        clean = " ".join(value.split())
        return clean if self.unicode else clean.encode("latin-1", "replace").decode("latin-1")

    def heading(self, value: str, size: float = 13) -> None:
        self.doc.ln(2)
        self.doc.set_font(self.family, "" if self.unicode else "B", size)
        self.paragraph(value, size=size, height=size * 0.55, keep_font=True)
        self.doc.set_font(self.family, "", 10)

    def paragraph(
        self, value: str, *, size: float = 10, height: float = 5, keep_font: bool = False
    ) -> None:
        if not keep_font:
            self.doc.set_font(self.family, "", size)
        self.doc.multi_cell(
            0,
            height,
            self.text(value),
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
            wrapmode=WrapMode.CHAR,
            align="L",
        )

    def link(self, label: str, url: str) -> None:
        self.doc.set_font(self.family, "", 9)
        self.doc.multi_cell(
            0,
            4.5,
            self.text(label),
            link=url,
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
            wrapmode=WrapMode.CHAR,
            align="L",
        )


def render_pdf(report: ReportDocument, *, font_path: Path | None = None) -> bytes:
    pdf = _Pdf(font_path)
    pdf.doc.set_title(pdf.text(report.title))
    pdf.doc.set_author("Argus research platform")
    pdf.doc.set_creator("Argus")
    pdf.doc.set_subject(pdf.text(report.objective[:200]))
    pdf.heading(report.title, 16)
    pdf.paragraph(f"Objective: {report.objective}")
    pdf.paragraph(
        f"Generated {report.generated_at.date().isoformat()} - version {report.version} - "
        f"overall confidence {report.confidence:.0%} - quality {report.quality.overall:.0%}",
        size=9,
    )
    pdf.heading("Executive summary")
    pdf.paragraph(report.executive_summary)
    findings = {finding.ref: finding for finding in report.findings}
    pdf.heading("Findings by question")
    for index, section in enumerate(report.sections, start=1):
        pdf.heading(f"{index}. {section.question}", 11)
        if section.status == "insufficient_evidence":
            pdf.paragraph("Unknown - insufficient evidence.")
            continue
        pdf.paragraph(section.narrative)
        for ref in section.findings:
            finding = findings[ref]
            sources = ", ".join(sorted({c.source for c in finding.citations}))
            contested = ", contested" if finding.contested else ""
            pdf.paragraph(
                f"{ref} [{finding.kind}{contested}; confidence {finding.confidence:.2f}; "
                f"{finding.support}; sources {sources}]: {finding.statement}",
                size=9,
            )
    pdf.heading("Contradictions")
    if not report.contradictions:
        pdf.paragraph("No contradictions between sources were found.")
    for conflict in report.contradictions:
        pdf.paragraph(
            f"{conflict.a} vs {conflict.b} - {conflict.attribute}: {conflict.uncertainty} "
            f"(explanation: {_EXPLANATIONS.get(conflict.explanation, conflict.explanation)}; "
            f"{conflict.rationale})"
        )
    pdf.heading("Recommendations")
    for number, advice in enumerate(report.recommendations, start=1):
        refs = f" ({', '.join(advice.findings)})" if advice.findings else ""
        pdf.paragraph(f"{number}. {advice.text}{refs}")
    if not report.recommendations:
        pdf.paragraph("No recommendations.")
    pdf.heading("Limitations")
    for limitation in report.limitations:
        pdf.paragraph(f"- {limitation}")
    m = report.methodology
    pdf.heading("Methodology")
    pdf.paragraph(
        f"Questions: {m.questions} (answered {m.answered}). Findings: {_finding_counts(m)}."
        f" Sources cited: {m.sources}. Contradictions: {m.contradictions}. Models: "
        f"{', '.join(m.models) or '-'}. Prompts: {', '.join(m.prompts) or '-'}. Human "
        f"approvals: {', '.join(m.approvals) or 'none'}. Model cost: USD {m.cost_usd}."
    )
    pdf.heading("Appendix A - Evidence")
    for finding in report.findings:
        for citation in finding.citations:
            pdf.paragraph(
                f"{finding.ref} [{citation.evidence}] {citation.source}: “{citation.quote}”",
                size=9,
            )
    pdf.heading("Appendix B - Sources")
    for source in report.sources:
        reliability = (
            f"{source.reliability:.2f} ({source.trust_tier})"
            if source.reliability is not None
            else (source.trust_tier or "-")
        )
        pdf.paragraph(
            f"{source.key}: {_source_title(source)} - {source.source_type}; published "
            f"{_when(source.published_at)}; retrieved {_when(source.retrieved_at)}; reliability "
            f"{reliability}; extraction {source.extraction_method}; sha256 "
            f"{source.content_hash or '-'}",
            size=9,
        )
        link = safe_link(source.url)
        if link:
            pdf.link(link, link)
    return bytes(pdf.doc.output())
