"""Searchable knowledge: chunks of uploaded documents and collected web pages (ADR 0004).

One row carries the chunk text, its full-text vector (generated by PostgreSQL), its embedding and
every attribute retrieval filters on - organisation, project, classification, injection risk,
origin, publication date - so authorisation is part of the search query itself. Composite foreign
keys cascade: deleting a document or a snapshot deletes its chunks in the same transaction.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Final
from uuid import UUID

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    CheckConstraint,
    Computed,
    ForeignKeyConstraint,
    Index,
    Integer,
    LargeBinary,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column

from argus.infrastructure.db.base import Base, CreatedAt, UUIDPrimaryKey, sql_in
from argus.modules.llm.voyage import EMBEDDING_DIMENSIONS

ORIGINS: Final = ("document", "web")
FTS_CONFIGS: Final = ("english", "simple")
RISK_LEVELS: Final = ("none", "low", "medium", "high")
TSV_EXPRESSION: Final = (
    "CASE WHEN fts_config = 'english' THEN to_tsvector('english'::regconfig, text) "
    "ELSE to_tsvector('simple'::regconfig, text) END"
)


class DocumentChunk(Base, UUIDPrimaryKey, CreatedAt):
    __tablename__ = "document_chunks"

    organization_id: Mapped[UUID]
    project_id: Mapped[UUID]
    origin: Mapped[str] = mapped_column(String(16))
    document_id: Mapped[UUID | None]
    source_id: Mapped[UUID | None]
    snapshot_id: Mapped[UUID | None]
    ordinal: Mapped[int] = mapped_column(Integer)
    text: Mapped[str] = mapped_column(Text)
    char_start: Mapped[int] = mapped_column(Integer)
    char_end: Mapped[int] = mapped_column(Integer)
    page_start: Mapped[int | None] = mapped_column(Integer)
    page_end: Mapped[int | None] = mapped_column(Integer)
    content_hash: Mapped[bytes] = mapped_column(LargeBinary)
    token_estimate: Mapped[int] = mapped_column(Integer)
    title: Mapped[str | None] = mapped_column(String(300))
    classification: Mapped[int] = mapped_column(SmallInteger)
    published_at: Mapped[datetime | None]
    injection_level: Mapped[str] = mapped_column(String(8))
    fts_config: Mapped[str] = mapped_column(String(16))
    tsv: Mapped[Any] = mapped_column(TSVECTOR, Computed(TSV_EXPRESSION, persisted=True))
    embedding: Mapped[list[float] | None] = mapped_column(Vector(EMBEDDING_DIMENSIONS))
    embedding_model: Mapped[str | None] = mapped_column(String(64))

    __table_args__ = (
        ForeignKeyConstraint(
            ["organization_id", "project_id"],
            ["projects.organization_id", "projects.id"],
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["organization_id", "document_id"],
            ["documents.organization_id", "documents.id"],
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["organization_id", "source_id"],
            ["sources.organization_id", "sources.id"],
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["organization_id", "snapshot_id"],
            ["source_snapshots.organization_id", "source_snapshots.id"],
            ondelete="CASCADE",
        ),
        UniqueConstraint("organization_id", "id"),
        UniqueConstraint("document_id", "ordinal"),
        UniqueConstraint("snapshot_id", "ordinal"),
        CheckConstraint(f"origin IN {sql_in(ORIGINS)}", name="origin"),
        CheckConstraint(f"fts_config IN {sql_in(FTS_CONFIGS)}", name="fts_config"),
        CheckConstraint(f"injection_level IN {sql_in(RISK_LEVELS)}", name="injection_level"),
        CheckConstraint("classification BETWEEN 0 AND 3", name="classification"),
        CheckConstraint(
            "(origin = 'document' AND document_id IS NOT NULL AND snapshot_id IS NULL"
            " AND source_id IS NULL) OR (origin = 'web' AND document_id IS NULL"
            " AND snapshot_id IS NOT NULL AND source_id IS NOT NULL)",
            name="parent",
        ),
        CheckConstraint("(embedding IS NULL) = (embedding_model IS NULL)", name="embedding_model"),
        CheckConstraint("char_end > char_start", name="offsets"),
        Index("ix_document_chunks_scope", "organization_id", "project_id", "classification"),
        Index("ix_document_chunks_document", "document_id"),
        Index("ix_document_chunks_source", "source_id"),
        Index("ix_document_chunks_snapshot", "snapshot_id"),
        Index("ix_document_chunks_tsv", "tsv", postgresql_using="gin"),
        Index(
            "ix_document_chunks_embedding",
            "embedding",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
    )
