"""Declarative base, naming convention and reusable column mixins."""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from sqlalchemy import ARRAY, DateTime, MetaData, Text, Uuid, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from argus.core.clock import utcnow
from argus.core.ids import uuid7

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def sql_in(values: tuple[str, ...] | list[str]) -> str:
    """``('a', 'b')`` for CHECK constraints over fixed, code-defined vocabularies."""
    for value in values:
        if not value.replace("_", "").replace("-", "").replace(":", "").replace(".", "").isalnum():
            msg = f"unsafe vocabulary value: {value!r}"
            raise ValueError(msg)
    return "(" + ", ".join(f"'{value}'" for value in values) + ")"


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    type_annotation_map = {
        datetime: DateTime(timezone=True),
        UUID: Uuid(as_uuid=True),
        dict[str, Any]: JSONB,
        list[str]: ARRAY(Text),
    }


class UUIDPrimaryKey:
    """UUIDv7 primary key generated by the application (no RETURNING round trip needed)."""

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid7)


class Timestamps:
    """Application-side defaults keep inserts free of ``RETURNING`` (see the RLS note in ADR 0002);
    the server defaults cover rows written by raw SQL and migrations."""

    created_at: Mapped[datetime] = mapped_column(default=utcnow, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        default=utcnow, onupdate=utcnow, server_default=func.now()
    )


class CreatedAt:
    created_at: Mapped[datetime] = mapped_column(default=utcnow, server_default=func.now())
